navikt/familie-klage

src/test/kotlin/no/nav/familie/klage/ApplicationLocal.kt, src/test/kotlin/no/nav/familie/klage/ApplicationLocalPostgres.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingsRepositoryTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/StegServiceTest.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/AuditLoggerMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/BrevClientMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieDokumentClientMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieIntegrasjonerMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/KabalClientMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/OppslagSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/PdlClientMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/pdfMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/db/DbContainerInitializer.kt, src/test/kotlin/no/nav/familie/klage/repository/FagsakRepositoryTest.kt, src/test/kotlin/no/nav/familie/klage/repository/RepositoryTest.kt, src/test/kotlin/no/nav/familie/klage/testutil/BrukerContextUtil.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt, src/test/kotlin/no/nav/familie/klage/testutil/PdlTestdataHelper.kt, src/test/kotlin/no/nav/familie/klage/testutil/TestoppsettService.kt, src/test/kotlin/no/nav/familie/klage/testutil/TokenUtil.kt
Tror det vært en rename av package i main men ikke i test, så då blir ikke mocks med i konfigen
=> Flytter testfiler til package uten ef i navnet

src/main/kotlin/no/nav/familie/klage/infrastruktur/config/KafkaConfig.kt, src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt
Beholder utkommentert kode som gjør det enkelt å lese topic fra start ved behov
=> Forbedrer navngivning

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/StegService.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/config/KafkaConfig.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/PersonopplysningerService.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/StegServiceTest.kt, src/test/kotlin/no/nav/familie/klage/repository/FagsakRepositoryTest.kt
For å gjøre det likt som i andre familie-repoer
=> Rename til behandlingrepository

src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt, src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt, src/test/kotlin/no/nav/familie/klage/behandling/StegServiceTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/domain/BehandlingStatusTest.kt, src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
Vil ferdigstille behandling når vi får "klageAvsluttet" events fra kabal.
=> Klage kafka ferdigstillbehandling

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingRepository.kt, src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/distribusjon/DistribusjonService.kt, src/main/kotlin/no/nav/familie/klage/kabal/KabalService.kt, src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt, src/main/kotlin/no/nav/familie/klage/kabal/event/OpprettOppgaveTask.kt, src/main/resources/db/migration/V17__behandling_ekstern_id.sql, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/klage/distribusjon/DistribusjonServiceTest.kt, src/test/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingControllerTest.kt, src/test/kotlin/no/nav/familie/klage/kabal/KabalServiceTest.kt, src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt, src/test/kotlin/no/nav/familie/klage/kabal/event/OpprettOppgaveTaskTest.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
Lagt til ny eksternBehandlingId som er unik for hver behandling som vi sender rundt til andre systemer
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9613
=> Endret navn på eksternBehandlingId til eksternFagsystemBehandlingId

src/main/kotlin/no/nav/familie/klage/behandling/StegService.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/behandlingshistorikk/BehandlingshistorikkController.kt, src/main/kotlin/no/nav/familie/klage/behandlingshistorikk/BehandlingshistorikkService.kt, src/main/kotlin/no/nav/familie/klage/behandlingshistorikk/domain/Behandlingshistorikk.kt, src/main/kotlin/no/nav/familie/klage/distribusjon/FerdigstillBehandlingService.kt, src/test/kotlin/no/nav/familie/klage/behandling/StegServiceTest.kt, src/test/kotlin/no/nav/familie/klage/distribusjon/FerdigstillBehandlingServiceTest.kt
* Hvis neste steg er ferdigstill, legg inn ferdigstill i historikken
* Hvis neste steg er KABAL_VENTER_SVAR, legg inn historikk for OVERFØRING_TIL_KABAL for å vise at vi har sendt til kabal, men ikke mottatt svar
Avhengig av:
* https://github.com/navikt/familie-klage-frontend/pull/26
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9672
=> Behandlingshistorikk kabal og ferdigstill

.deploy/azure-ad-app-lokal.yaml, .deploy/preprod.yaml, .deploy/prod.yaml, src/main/kotlin/no/nav/familie/klage/infrastruktur/config/RolleConfig.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/sikkerhet/SikkerhetContext.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingControllerTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/StegServiceTest.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/OppslagSpringRunnerTest.kt, src/test/resources/application-local.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9430
=> Lagt til støtte for rollevalidering for flere fagsystemer

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/sikkerhet/TilgangService.kt, src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieIntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/klage/journalpost/JournalpostService.kt, src/main/kotlin/no/nav/familie/klage/vedlegg/DokumentInfoDto.kt, src/main/kotlin/no/nav/familie/klage/vedlegg/VedleggController.kt, src/main/kotlin/no/nav/familie/klage/vedlegg/VedleggService.kt, src/test/kotlin/no/nav/familie/klage/journalpost/JournalpostServiceTest.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt, src/test/kotlin/no/nav/familie/klage/vedlegg/VedleggControllerIntegrasjonsTest.kt, src/test/kotlin/no/nav/familie/klage/vedlegg/VedleggServiceTest.kt
[favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9408)
Hører sammen med frontend PR: https://github.com/navikt/familie-klage-frontend/pull/73
=> Dokumentoversikt

src/main/kotlin/no/nav/familie/klage/behandling/OpprettBehandlingService.kt, src/test/kotlin/no/nav/familie/klage/behandling/OpprettBehandlingServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9696)
=> skal ikke kunne opprette klage med krav mottatt frem i tid

src/main/resources/db/migration/V20__opprydding.sql
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9621
=> Opprydding av database før baseline

src/main/kotlin/no/nav/familie/klage/vurdering/VurderingController.kt, src/main/kotlin/no/nav/familie/klage/vurdering/VurderingRepository.kt, src/main/kotlin/no/nav/familie/klage/vurdering/VurderingService.kt, src/main/kotlin/no/nav/familie/klage/vurdering/VurderingValidator.kt, src/main/kotlin/no/nav/familie/klage/vurdering/domain/Vurdering.kt, src/main/kotlin/no/nav/familie/klage/vurdering/dto/VurderingDto.kt, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingControllerTest.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt, src/test/kotlin/no/nav/familie/klage/vurdering/VurderingValidatorTest.kt
Sjekk commits for hva som er endret
=> Vurdering opprydding, plus validering av vurderingDto

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevController.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt, src/main/kotlin/no/nav/familie/klage/brev/domain/Brev.kt, src/main/kotlin/no/nav/familie/klage/felles/domain/Fil.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/config/DatabaseConfiguration.kt, src/main/resources/db/migration/V4__brev_pdf.sql, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingFlytTest.kt, src/test/kotlin/no/nav/familie/klage/brev/BrevServiceTest.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9812
* https://github.com/navikt/familie-klage-frontend/pull/89
=> Skal hente brev fra basen når en behandling er "ferdigstilt"

src/main/kotlin/no/nav/familie/klage/infrastruktur/config/PdlConfig.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/PersonopplysningerController.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/PersonopplysningerService.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/dto/PersonopplysningerDto.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlClient.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlPerson.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlPersonRequest.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlPersonRequestVariables.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlPersonUtil.kt, src/main/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlUtil.kt, src/main/resources/pdl/navn_bolk.graphql, src/main/resources/pdl/søker.graphql, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieIntegrasjonerMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/PdlClientMock.kt, src/test/kotlin/no/nav/familie/klage/personopplysninger/PersonopplysningerServiceTest.kt, src/test/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlDtoTest.kt, src/test/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlTestdata.kt, src/test/kotlin/no/nav/familie/klage/testutil/PdlTestdataHelper.kt, src/test/resources/application-integrasjonstest.yaml, src/test/resources/application-local.yml
Splittet i 2 commits
1. for å fjerne deler vi ikke trenger fra PDL
2. Henting av relevant data
Koblet til 
* https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9926
* https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9965
=> Pdl opprydding og hente relevant data

.github/workflows/manual-deploy-kafka-topic.yml, kafka/aapen-klage-behandlingsstatistikk/behandlingsstatistikk-topic-dev.yaml, kafka/aapen-klage-behandlingsstatistikk/behandlingsstatistikk-topic-prod.yaml
Lager ikke deploy-script for prod enda, tilfelle det er ønske om endringer i config/kontrakter etc. Legger til deploy mot prod senere.
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9757
=> Opprett kafka-topic for behandlingsstatistikk

src/main/kotlin/no/nav/familie/klage/vurdering/VurderingService.kt, src/main/kotlin/no/nav/familie/klage/vurdering/domain/Vurdering.kt, src/main/kotlin/no/nav/familie/klage/vurdering/dto/VurderingDto.kt, src/main/resources/db/migration/V7__internt_notat.sql, src/test/kotlin/no/nav/familie/klage/ApplicationLocalPostgres.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10086
=> Skal støtte internt notat ved vurdering

src/main/kotlin/no/nav/familie/klage/behandling/OpprettBehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/behandlingshistorikk/BehandlingshistorikkController.kt, src/main/kotlin/no/nav/familie/klage/behandlingshistorikk/BehandlingshistorikkService.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingFlytTest.kt
Løser [dette kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9913)
(Får nå historikkinnslag på henlagt og behandling opprettet
Edit: Henlagt er løst i frontend: 
* https://github.com/navikt/familie-klage-frontend/pull/131
=> Utbedre hendelseshistorikk

src/main/kotlin/no/nav/familie/klage/blankett/BlankettPdfRequest.kt, src/main/kotlin/no/nav/familie/klage/blankett/BlankettService.kt, src/test/kotlin/no/nav/familie/klage/blankett/BlankettServiceTest.kt, src/test/resources/blankett/request.json
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10092
* https://github.com/navikt/familie-ef-blankett/pull/104
=> Blankett skal vise info om påklaget vedtak

src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt
Etter tilbakemeldinger fra Lars og Mirja.
Brev spesifisert her: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10143
=> Tekstendringer oversendelsesbrev

src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt
Denne forsvant visst i en git-konflikt.
=> Tekstendring etter tilbakemeldinger fra Mirja

src/main/kotlin/no/nav/familie/klage/distribusjon/DistribusjonService.kt, src/test/kotlin/no/nav/familie/klage/distribusjon/DistribusjonServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10255
=> Skal ha tittel på brev utifra behandlingsresultat

src/main/kotlin/no/nav/familie/klage/behandlingsstatistikk/BehandlingsstatistikkService.kt, src/main/kotlin/no/nav/familie/klage/blankett/BlankettPdfRequest.kt, src/main/kotlin/no/nav/familie/klage/blankett/BlankettService.kt, src/main/kotlin/no/nav/familie/klage/vurdering/VurderingService.kt, src/main/kotlin/no/nav/familie/klage/vurdering/VurderingValidator.kt, src/main/kotlin/no/nav/familie/klage/vurdering/domain/Vurdering.kt, src/main/kotlin/no/nav/familie/klage/vurdering/dto/VurderingDto.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt, src/test/resources/blankett/request.json
Må også oppdateres:
* https://github.com/navikt/familie-ef-blankett/pull/108
* https://github.com/navikt/familie-klage-frontend/pull/162
=> vurdering sin årsak skal skrives med å: arsak -> årsak

src/main/kotlin/no/nav/familie/klage/brev/FormBrevUtil.kt, src/test/kotlin/no/nav/familie/klage/brev/FormBrevUtilTest.kt
* Tekstutbedringer i brev etter tilbakemeldinger
=> tekstutbedringer i brev etter tilbakemeldinger fra brukertest.

src/main/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingController.kt, src/main/kotlin/no/nav/familie/klage/vurdering/VurderingController.kt, src/main/kotlin/no/nav/familie/klage/vurdering/VurderingService.kt, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingControllerTest.kt
Ymse todo-fikser.
Gjenstår et par til, men der må det gås opp en litt større løype
=> Todo fixes

kafka/aapen-klage-behandlingsstatistikk/behandlingsstatistikk-topic-dev.yaml, kafka/aapen-klage-behandlingsstatistikk/behandlingsstatistikk-topic-prod.yaml
Statistikk ønsker å endre appnavn
=> Retter på application name for aapen-klage-behandlingsstatistikk

pom.xml, src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/OpprettBehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandlingsstatistikk/PatchBehandlingsstatistikkController.kt, src/main/kotlin/no/nav/familie/klage/distribusjon/JournalførBrevTask.kt, src/main/kotlin/no/nav/familie/klage/formkrav/FormService.kt, src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt, src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveTaskService.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/klage/distribusjon/JournalførBrevTaskTest.kt, src/test/kotlin/no/nav/familie/klage/formkrav/FormServiceTest.kt, src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt, src/test/kotlin/no/nav/familie/klage/oppgave/OppgaveTaskServiceTest.kt
Ny prosessering som har satt taskRepository til internal
=> Bruker taskService i stedet for taskRepository

src/main/kotlin/no/nav/familie/klage/vurdering/domain/Vurdering.kt
Denne finnes i frontend men ikke backend
=> Legger til hjemmel for tilbakekreving 22.15

src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt, src/main/kotlin/no/nav/familie/klage/distribusjon/DistribusjonService.kt, src/main/kotlin/no/nav/familie/klage/felles/util/StønadstypeVisningsnavn.kt, src/test/kotlin/no/nav/familie/klage/brev/BrevInnholdTest.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieEFSakClientMock.kt
…ling
Trenger ikke å ha med tilbakekreving i selve tittelen på journalposten
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10404
=> Vedtaksbrev tilbakekreving

src/main/kotlin/no/nav/familie/klage/behandling/dto/BehandlingDto.kt, src/main/kotlin/no/nav/familie/klage/behandling/dto/PåklagetVedtakDetaljerMapper.kt, src/main/kotlin/no/nav/familie/klage/formkrav/FormService.kt, src/main/kotlin/no/nav/familie/klage/formkrav/dto/FormkravDto.kt, src/test/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingControllerTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10461
=> Skal returnere påklaget vedtak til frontend

src/main/kotlin/no/nav/familie/klage/formkrav/FormService.kt, src/main/kotlin/no/nav/familie/klage/formkrav/FormUtil.kt, src/test/kotlin/no/nav/familie/klage/formkrav/FormServiceTest.kt, src/test/kotlin/no/nav/familie/klage/formkrav/FormUtilTest.kt
Synes det var litt vanskelig å skjønne flytet for validering her, så har gjenbrukt selve formvilkår som resultat
Plukker ut fra https://github.com/navikt/familie-klage/pull/200/files#diff-838a708211eb6fc842da7e0f8b6d170df15e3ccdaa99300a78995a9d196391ff
Se diskusjon https://github.com/navikt/familie-klage/pull/201/files#r1038125360
=> Fortydliget flyt og validering av av formkrav

pom.xml, src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/FagsystemRevurdering.kt, src/main/kotlin/no/nav/familie/klage/behandling/dto/BehandlingDto.kt, src/main/kotlin/no/nav/familie/klage/fagsak/FagsakRepository.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/config/DatabaseConfiguration.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakService.kt, src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieEFSakClient.kt, src/main/kotlin/no/nav/familie/klage/test/TestController.kt, src/main/resources/db/migration/V17__behandling_fagsystem_revurdering.sql, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingRepositoryTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingServiceIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/domain/FagsystemRevurderingTest.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieEFSakClientMock.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt, src/test/kotlin/no/nav/familie/klage/testutil/FeatureToggleTestUtil.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
* https://github.com/navikt/familie-klage-frontend/pull/243
* https://github.com/navikt/familie-ef-sak/pull/1952
=> Oppretter revurdering automatisk ved medhold

src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieEFSakClient.kt
Fix av https://github.com/navikt/familie-klage/pull/210
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
=> Opprett revurdering skal bruke post

pom.xml, src/main/kotlin/no/nav/familie/klage/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakService.kt, src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieEFSakClient.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieEFSakClientMock.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
=> Brevfanen skal vise info om revurdering kommer bli opprettett automatisk

src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
=> Skal toggle frontend om man skal vise info om opprett-revurdering

src/main/kotlin/no/nav/familie/klage/behandlingsstatistikk/BehandlingsstatistikkTask.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
=> Skal rydde vekk toggles for startBehandling og behandlingsstatistikk

src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt, src/main/kotlin/no/nav/familie/klage/formkrav/FormUtil.kt, src/test/kotlin/no/nav/familie/klage/brev/BrevInnholdTest.kt, src/test/kotlin/no/nav/familie/klage/brev/BrevServiceTest.kt, src/test/kotlin/no/nav/familie/klage/formkrav/FormUtilTest.kt
[Løser dette kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10241)
Frontend:
* https://github.com/navikt/familie-klage-frontend/pull/264
=> Ikke påklaget vedtak avvisning

pom.xml, src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/behandling/dto/BehandlingDto.kt, src/main/kotlin/no/nav/familie/klage/behandling/dto/PåklagetVedtakDetaljerMapper.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingServiceIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10666
=> Skal kunne velge utestengelse som påklaget vedtak

src/main/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakService.kt, src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClient.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakServiceTest.kt, src/test/resources/application-local.yml
Hopper bukk over DVH og brev i denne omgang, det kommer i en senere PR
=> Legg til KS-kall og bruk dem i FagsystemVedtakService.kt

src/main/resources/application-dev.yml, src/main/resources/application.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10604
=> Tar i bruk q2

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/test/kotlin/no/nav/familie/klage/behandling/OpprettBehandlingServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10793
=> Skal kunne ha flere åpne klager på samme fagsak

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/behandling/dto/BehandlingDto.kt, src/main/kotlin/no/nav/familie/klage/behandling/dto/PåklagetVedtakDetaljerMapper.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingServiceTest.kt
Oppgave [Tea-10933](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10933)
Hører sammen med [PR 331](https://github.com/navikt/familie-klage-frontend/pull/331) i familie-klage-frontend
=> Ordinært vedtak infotrygd som ny PåklagetVedtaksType

.deploy/preprod.yaml, .deploy/prod.yaml, src/main/kotlin/no/nav/familie/klage/amelding/InntektController.kt, src/main/kotlin/no/nav/familie/klage/amelding/InntektService.kt, src/main/kotlin/no/nav/familie/klage/amelding/ekstern/AMeldingInntektClient.kt, src/test/kotlin/no/nav/familie/klage/ApplicationLocalPostgres.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/AInntektMock.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/OppslagSpringRunnerTest.kt
Backend til følgende PR:
- https://github.com/navikt/familie-klage-frontend/pull/332
Testet i preprod ✅
=> Eksterne lenker

src/main/kotlin/no/nav/familie/klage/kabal/domain/KabalHjemmel.kt, src/main/kotlin/no/nav/familie/klage/vurdering/domain/Vurdering.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11006
=> Legger inn hjemmel for 22-12 og 22-13

.github/tag.sh
Ref https://github.com/navikt/familie-klage/issues/250
=> Skal bruke main som trunk i tag-script

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/OpprettRevurderingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/OpprettRevurderingUtil.kt, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/OpprettRevurderingServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11378
Skal ikke opprette automatisk revurdering for tilbakekreving, eller utestengelse
=> Skal kun opprette automatisk revurdering kun på vedtak i fagsystemene

pom.xml, src/main/kotlin/no/nav/familie/klage/felles/domain/AuditLogger.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/config/RolleConfig.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/sikkerhet/TilgangInterceptor.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/klage/testutil/BrukerContextUtil.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11344
Anbefaler å gå igjennom
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
* https://github.com/navikt/familie-felles/pull/661
* https://github.com/navikt/familie-kontrakter/pull/732
=> Spring boot 3

.deploy/preprod.yaml, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/resources/application-local.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-11924
* https://github.com/navikt/familie-klage-frontend/pull/400
=> Ny ingress i dev

LICENSE
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-9736
=> Legger til MIT-lisensfil

src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt
Etter bestilling fra Mirja: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12454
Vil bytte ut 
```
Du finner informasjon som kan være nyttig for deg på nav.no/alene-med-barn. Du kan også kontakte oss på nav.no/kontakt.
``` 
med
```
Du finner mer informasjon på nav.no/alene-med-barn. 
På nav.no/kontakt kan du chatte eller skrive til oss. 
Hvis du ikke finner svar på nav.no kan du ringe oss på telefon 55 55 33 33, hverdager 09.00-15.00. 
```
**Før**
**Etter**
=> Tekstendring brevavslutning

src/main/kotlin/no/nav/familie/klage/felles/domain/AuditLogger.kt
Ref: https://nav-it.slack.com/archives/CH4NLKAR0/p1689237228023819?thread_ts=1689077799.460959&cid=CH4NLKAR0
=> Bugfix: Fjerner en header som ikke lenger skal være med etter det ble lagt til navn på PO

.deploy/preprod.yaml, .deploy/prod.yaml, .deploy/unleash-apitoken-preprod.yaml, .deploy/unleash-apitoken-prod.yaml, .github/workflows/deploy-unleash-api-token.yaml
Hvorfor er denne endringen nødvendig? ✨
Unleash Next skal taes i bruk i stedet for gamle Unleash. Trenger derfor å kunne opprette api-tokens i dev og prod for Unleash Next : https://docs.nais.io/addons/unleash-next/?h=unleash+nex#creating-a-new-api-token
Lager en workflow som trigges manuelt og som antakeligvis bare trengs og kjøres én gang. 
Favro : https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-14466
=> Oppretter workflow for generering av Unleash Next api-token.

.github/dependabot.yml, pom.xml
.. og grupperer dependabot PR'er
=> Oppdater avhengigheter

.github/dependabot.yml
Vil bruke reader token (fjerner PAT)
=> Bruk secrets.READER_TOKEN

.github/workflows/codeql.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, pom.xml
Fiks av Codeql og bytte fra ghcr til GAR/docker-push
=> Fikser codeql + gå over til GAR

.deploy/preprod.yaml, src/main/kotlin/no/nav/familie/klage/behandling/BehandlingController.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveClient.kt, src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveService.kt, src/main/kotlin/no/nav/familie/klage/oppgave/TilordnetRessursService.kt, src/main/kotlin/no/nav/familie/klage/oppgave/dto/SaksbehandlerDto.kt, src/test/kotlin/no/nav/familie/klage/oppgave/OppgaveServiceTest.kt
[Frontend PR](https://github.com/navikt/familie-klage-frontend/pull/823)
=> Endepunkt for ansvarlig saksbehandler

.github/workflows/build-dev.yml
[NAV-22116](https://favro.com/organization/98c34fb974ce445eac854de0/?card=NAV-22116)
Anbefalt å sjekke på måten
github.event.pull_request.user.login != 'dependabot[bot]'
=> Bytter ut github actor med github.event.pull_request.user.login for sikrere bygg

src/main/resources/pdl/pdl-api-schema.graphql
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-21643
=> Endrer fra Fødsel til Fødselsdato og Fødested i pdl-spesifikasjon

src/main/kotlin/no/nav/familie/klage/behandling/dto/BehandlingDto.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22595)
=> skal sende med klagebehandlingsårsak til frontend

src/main/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingService.kt, src/main/kotlin/no/nav/familie/klage/behandling/StegService.kt, src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt, src/main/kotlin/no/nav/familie/klage/blankett/BlankettPdfRequest.kt, src/main/kotlin/no/nav/familie/klage/blankett/BlankettService.kt, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/klage/behandling/StegServiceTest.kt, src/test/kotlin/no/nav/familie/klage/søk/SøkControllerTest.kt, src/test/resources/blankett/request.json
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22595). 
Denne PRen gjør slik at behandlinger med årsak `henvendelse fra kabal` ikke journalfører og distribuerer brev.
=> Ferdigstill behandling uten brev

src/main/kotlin/no/nav/familie/klage/brev/domain/Brev.kt, src/main/kotlin/no/nav/familie/klage/distribusjon/SendTilKabalTask.kt, src/main/kotlin/no/nav/familie/klage/kabal/KabalService.kt, src/main/kotlin/no/nav/familie/klage/kabal/domain/OversendtKlage.kt, src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingServiceTest.kt, src/test/kotlin/no/nav/familie/klage/kabal/KabalServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22690)
=> Skal oversende fullmektig til kabal

src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23087
=> Endrer lenke til klage

pom.xml, src/main/kotlin/no/nav/familie/klage/brev/BrevInnholdUtleder.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevsignaturService.kt, src/main/kotlin/no/nav/familie/klage/brev/avvistbrev/AvvistBrevInnholdUtleder.kt, src/main/kotlin/no/nav/familie/klage/brev/avvistbrev/Formkrav.kt, src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt, src/main/kotlin/no/nav/familie/klage/kabal/KabalService.kt, src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt, src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
https://nav-it.slack.com/archives/C058Z17RTSR/p1731332841782139
=> Oppdater kontrakter med ny enum: OMGJOERINGSKRAVBEHANDLING_AVSLUTTET

pom.xml, src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23825
Oppdatering til spring 3.4.1, bumper også andre relevante pakker samtidig
=> Oppdater til spring 3.4.1

src/test/kotlin/no/nav/familie/klage/infrastruktur/config/PdlClientMock.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23920
Legger til Stønadstype.BARNETRYGD for å gjøre det enklere for BAKS å teste lokalt.
=> NAV-23920: Legger til BARNETRYGD i PdlClientMock

src/main/kotlin/no/nav/familie/klage/distribusjon/SendTilKabalTask.kt, src/main/kotlin/no/nav/familie/klage/kabal/KabalClient.kt, src/main/kotlin/no/nav/familie/klage/oppgave/OpprettKabalEventOppgaveTask.kt, src/test/kotlin/no/nav/familie/klage/distribusjon/SendTilKabalTaskTest.kt, src/test/kotlin/no/nav/familie/klage/oppgave/OpprettKabalEventOppgaveTaskTest.kt
Satser på at vi kan fange HttpClientErrorException - det burde jo faktisk kastes - litt vanskelig å "teste". Andre forslag evt ?
=> Catcher HttpClientErrorException i stedet for å wrappe i Ressurs

src/main/kotlin/no/nav/familie/klage/brev/BrevClient.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
Fortsettelse av denne: https://github.com/navikt/familie-klage/pull/599
=> Bruk riktig type med datasett avhengig av stønadtype

src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/klage/kabal/BehandlingFeilregistrertTask.kt, src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt, src/main/kotlin/no/nav/familie/klage/oppgave/OpprettBehandleSakOppgaveTask.kt, src/test/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingControllerTest.kt, src/test/kotlin/no/nav/familie/klage/kabal/BehandlingFeilregistrertTaskTest.kt, src/test/kotlin/no/nav/familie/klage/testutil/DtoTestUtil.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24542
Ref favrokortet, så er behandlingstema.klage lagt inn ved feil i kontrakter.
Før denne slettes må vi her begynne å bruke behandlingstype istedenfor.
=> Bruker behandlingstype istedenfor behandlingstema klage

src/main/kotlin/no/nav/familie/klage/blankett/BlankettPdfRequest.kt, src/main/kotlin/no/nav/familie/klage/blankett/BlankettService.kt, src/test/kotlin/no/nav/familie/klage/blankett/BlankettServiceTest.kt, src/test/resources/blankett/request.json
Legger til nye felter for BA og KS i Vurdering over i VurderingBlankettDto
Se endringer i [familie-brev](https://github.com/navikt/familie-brev/pull/769)
=> Legg til felter i BlankettVurderingDto for BA og KS

src/main/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakService.kt
Favro: [NAV-24779](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24779)
Dersom opprettelse av revurdering feiler slik løsningen er nå, vil klage-behandlingen bli ferdigstilt og det vises et varsel om at saksbehandler må opprette revurderingen manuelt i fagsystemet (EF, BA eller KS). 
For BA og KS ønsker vi nå å hindre ferdigstilling av klage-behandling dersom opprettelse av revurdering feiler. Løser dette ved å kaste feil dersom opprettelse av revurdering feiler og fagsystem er BA eller KS. Da vil saksbehandler bli stående på "Brev"-fanen med en feilmelding som sier "Opprettelse av revurdering feilet. Prøv igjen senere".
[Tilhørende frontend PR.](https://github.com/navikt/familie-klage-frontend/pull/921)
Skjermbilder:
=> NAV-24779: Kaste feil dersom opprettelse av revurdering feiler

src/main/kotlin/no/nav/familie/klage/behandling/BehandlingPåVentService.kt
Fjerner dobbelt opp av save task for statistikk når behandling settes på vent.
=> Fjerner double save av statistikk task.

.github/dependabot.yml, .github/workflows/build-dev.yml, .github/workflows/codeql.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-unleash-api-token.yaml, .github/workflows/manual-deploy-kafka-topic.yml
Brukt ratchet til å pinne workflows til sha av sikkerhetsgrunner
=> Pinner actions til sha

.github/dependabot.yml
=> Fiks indent i dependabot.yml

.nais/app-dev.yaml, .nais/app-prod.yaml, src/main/resources/logback-spring.xml
Sender secureLogger også til Teamlogs
=> Sikker logging med team-logs

src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt, src/test/kotlin/no/nav/familie/klage/integrasjoner/FeatureToggleMock.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25151
Fjerner toggle da den har vært på i prod en stund allerede.
=> NAV-25151: Fjerner toggle for å endre behandlende enhet

src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClient.kt
I forrige PR hadde jeg ikke fjernet nok fra url 🙃
=> Korrigerer url for tilgangssjekk KS

src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt, src/main/kotlin/no/nav/familie/klage/infrastruktur/sikkerhet/TilgangService.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/sikkerhet/TilgangServiceTest.kt
Fjerner toggle for å ta i bruk ny tilgangskontroll for ba og ks.
Flytter også noe duplikat kode inn i egen funksjon.
=> Fjerner toggle for bruk av ny tilgangsjekk for baks

src/main/kotlin/no/nav/familie/klage/brev/BrevClient.kt, src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt, src/test/kotlin/no/nav/familie/klage/behandling/BehandlingFlytTest.kt, src/test/kotlin/no/nav/familie/klage/brev/BrevServiceTest.kt, src/test/kotlin/no/nav/familie/klage/infrastruktur/config/BrevClientMock.kt
Tilhørende PRs:
* https://github.com/navikt/familie-brev/pull/810
* https://github.com/navikt/familie-klage-frontend/pull/996
=> skal sende med brevmottakere for brevgenerering
