navikt/familie-klage

- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingRepository.kt
- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/klage/behandling/domain/Behandling.kt
- src/test/kotlin/no/nav/familie/klage/behandling/BehandlingServiceIntegrasjonsTest.kt
Det skal ikke være mulig å opprette en ny klagebehandling dersom det allerede eksisterer en behandling på samme fagsak, og denne behandlingen er "under arbeid av saksbehandlinger" -> Dvs. stegType er `opprettet` eller `utredes`
> Valider opprettelse behandling

- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/FormController.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/FormRepository.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/FormService.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/FormUtil.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/domain/Form.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/dto/FormDto.kt
- src/main/resources/db/migration/V19__formresultat.sql
- src/test/kotlin/no/nav/familie/klage/FlytTest.kt
- src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/formkrav/FormServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/formkrav/FormUtilTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
* Fjerner avhengighet til fagsakId i form
* Endrer controller til å motta FormDto og ikke domeneobjekt
* Flytter ut valideringsmetoder til utils, og lager noen enkle tester for disse
* Endrer opprettEllerOppdaterFormkravVilkår til å kun oppdatere, då vi initierer de i en egen metode når man oppretter behandlingen
* Flytter default values inn i domeneobjektet, og bruker det for initiell initiering, er det greit? [a2da966](https://github.com/navikt/familie-klage/pull/51/commits/a2da9667867465dc9a85b7f5d06e6bbfa0866488)
> Formkrav opprydding

- src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/brev/FormBrevUtil.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/FormUtil.kt
- src/test/kotlin/no/nav/familie/klage/brev/FormBrevUtilTest.kt
Skal sende med brevtekst til frontend, bassert på fritekst i formkravfane. Forskjellig tekst skal vises basert på hvilke formkrav som ikke er oppfylte.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10172)
[Design](https://www.figma.com/file/JEmXg4WqG0DFItNGpoX696/Skisser-EF-sak?node-id=9854%3A148394)
Eksempel:
> Formkravtekst inn i brev

- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingService.kt
- src/main/kotlin/no/nav/familie/klage/behandling/dto/BehandlingDto.kt
- src/main/kotlin/no/nav/familie/klage/behandling/dto/PåklagetVedtakDetaljerMapper.kt
Opprydding etter [påklaget vedtak utestengelse](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10666).
`vedtaksdatoInfotrygd` er erstattet av `manuellVedtaksdato`, og brukes ikke lengre i frontend.
Venter litt med å merge så saksbehandlere får ny versjon av frontend.
> Fjern bruk av deprecated felt vedtaksdatoInfotrygd

- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClient.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClient.kt
Det hadde sneket seg inn en ekstra `/behandling/` i URLene for å opprette revurdering. Fjerner det i denne PRen
> Fiks BA og KS urler for å opprette revurdering

- pom.xml
- src/main/kotlin/no/nav/familie/klage/behandling/OpprettBehandlingService.kt
- src/main/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingController.kt
- src/main/kotlin/no/nav/familie/klage/felles/util/TaskMetadata.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveClient.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveService.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveTaskService.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OpprettBehandleSakOppgaveTask.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OpprettKabalEventOppgaveTask.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/OpprettOppgaveTaskTest.kt
- src/test/kotlin/no/nav/familie/klage/oppgave/OppgaveServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/oppgave/OppgaveTaskServiceTest.kt
Saksbehandlere skal ha muligheten til å huke av for at en klage gjelder tilbakekreving, som skal sette behandlingstemaet på behandle sak oppgaven til `ab0007` (tilbakekreving). 
For ef-sak skal dette skje både via journalføring og ved manuell opprettelse av en klage.
1. Setter behandlingstema til `ab0007` dersom `klageGjelderTilbakekreving` er true ved opprettelse av ny oppgave.
2. Lagt til et endepunkt som setter behandlingstema på en eksisterende oppgave til `ab0007`
- [PR i EF-sak](https://github.com/navikt/familie-ef-sak/pull/2160) (Sende med klageGjelderTilbakekreving og opprette task for kall på nytt endepunkt)
- [PR i ef-sak-frontend](https://github.com/navikt/familie-ef-sak-frontend/pull/2254) (Legge til checkbokser for å huke av om klage gjelder tilbakekreving)
- [PR i …
> Skal sette behandlingstema = ab0007 på klager som gjelder tilbakekreving

- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveService.kt
- src/test/kotlin/no/nav/familie/klage/oppgave/OppgaveServiceTest.kt
**Bakgrunn:** Task `oppdaterOppgaveTilÅGjeldeTilbakekreving` feiler med melding "kan ikke oppdatere ferdigstilte oppgaver" fra oppgavesystemet. 
Dette kommer av at det er mulig å journalføre på eksisterende ferdigstilte behandlinger, og dersom journalføringen både er klage og journalføring skal oppgaven markeres med eget behandlingstema. 
Droppe oppdatering av oppgave dersom behandling alt er ferdigstilt fordi målet med markeringen av "Klage - TIlbakekreving" er å unngå at feil SB plukker slike oppgaver, som ikke er et problem når behandlingen alt er ferdigstilt.
> Skal ikke oppdatere tema på oppgaver hvor behandlingen er alt er ferdigstilt

- pom.xml
- src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
**Hvorfor?**
[Kabal har lagt til ny eventtype BEHANDLING_FEILREGISTERT](https://nav-it.slack.com/archives/C058Z17RTSR/p1684918865152359), og disse må kunne leses av klage. Foreløpig vil vi bare feile dersom vi får en melding av den typen men i fremtiden kan vi vurdere om vi skal opprette oppfølgingsoppgave eller åpne/tilbakestille behandlingen i klage.
Vi har en favrooppgave for videre oppfølging: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12862
> Skal håndtere, men feile ved eventypen BEHANDLING_FEILREGISTRERT

- src/main/kotlin/no/nav/familie/klage/brev/BrevInnhold.kt
- src/main/kotlin/no/nav/familie/klage/kabal/BehandlingFeilregistrertTask.kt
- src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt
- src/main/kotlin/no/nav/familie/klage/kabal/domain/KlageinstansResultat.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/main/resources/db/migration/V19__årsak_feirlregistrert_klageresultat.sql
- src/test/kotlin/no/nav/familie/klage/kabal/BehandlingFeilregistrertTaskTest.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
**Hvorfor?**
Vi får ikke lest meldinger på kafka-køen fra kabal fordi vi feiler på håndtering av en BEHANDLING_FEILREGISTRERT-event. I stedenfor å feile lager vi heller en task som skal implementeres og følges opp av oss.
> Skal opprette task for å håndtere beahandling feilregistrert fra kabal

- pom.xml
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/main/kotlin/no/nav/familie/klage/kabal/BehandlingFeilregistrertTask.kt
- src/main/kotlin/no/nav/familie/klage/kabal/domain/KlageinstansResultat.kt
- src/test/kotlin/no/nav/familie/klage/kabal/BehandlingFeilregistrertTaskTest.kt
**Hvorfor?**
Vi har fått en feilregistrert klage i prod, og risikerer og få flere fremover. Disse må håndteres ved at vi oppretter en task, som videre ferdigstiller behandlingen og oppretter en oppfølgingsoppgave. Vi kommer til å ha featuretogglen for dette avskrudd, for å kunne følge opp de enkelte behandlingene.
Tråd på slack om aktuell sak i prod: https://nav-it.slack.com/archives/C01087QRJ2U/p1687333031507799
> Taskhåndtering feilregistrert klage

- pom.xml
- src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieIntegrasjonerMock.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
Vi har fått en ANKE_I_TRYGDERETTENBEHANDLING_OPPRETTET-event fra kabal på en av sakene våre: https://familie-klage.intern.nav.no/behandling/7af02491-4aeb-4cfe-924f-b2fcfa4e237d/resultat Vi må kunne lagre og håndtere dette resultatet. Etter diskusjon med Lars oppretter vi ingen oppfølgingsoppgaver for eventet. Vi kommer bare til å vise det midlertidige resultatet i klage-frontend.
**Relaterte PRer**
https://github.com/navikt/familie-ef-sak-frontend/pull/2416
https://github.com/navikt/familie-kontrakter/pull/810
> Skal kunne håndtere ANKE_I_TRYGDERETTENBEHANDLING_OPPRETTET-event fra kabal

- .deploy/preprod.yaml
- .deploy/prod.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
> Fjerner CPU-limit

- .deploy/preprod.yaml
- .deploy/prod.yaml
- pom.xml
- src/main/kotlin/no/nav/familie/klage/infrastruktur/config/ApplicationConfig.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/config/FeatureToggleConfig.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/main/resources/application.yml
- src/test/resources/application-integrasjonstest.yaml
- src/test/resources/application-local.yml
Hvorfor er denne endringen nødvendig? ✨
Oppsett for Unleash Next og fjerning av Unleash. Det fantes én toggle for familie-klage per i dag (familie.klage.henlegg-feilregistrert-behandling), som er opprettet her : https://teamfamilie-unleash-web.nav.cloud.nais.io/. Denne PRen fjerner koblingen til unleash.nais.io. 
Testet ok i dev. 
Favro : https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-14466
> Fjerner Unleash og legger til Unleash Next fra felles

- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
Fjerner toggle brukt til testing. Lar også settet av funksjonsbrytere i FeatureToggleController være tomt som det var i utgangspunktet. ~Fjerne controllerklassen ?~
> Fjerner test.environment toggle

- .github/dependabot.yml
Synes det blir litt mye å samle sammen alle avhengighetene i én dependabot-pr. 
Deler det opp slik at vi kun samler de som hører sammen:
> Kun samle avhengigheter som hører sammen

- src/main/kotlin/no/nav/familie/klage/brev/BrevClient.kt
Skal ta i bruk ny url mot familie-brev for generering av blankett.
Henger sammen med PR i familie-brev:
* https://github.com/navikt/familie-brev/pull/586
Testet i preprod ✅
> skal ta i bruk ny url mot familie-brev for generering av blankett

- Dockerfile
Hvorfor trengs denne endringen ?
Det virker unødvendig å ha egen distro inkludert i docker image, da dette er overflødig og gir potensielt mange sikkerhetshull.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-16237
> Endrer til distroless docker image

- .deploy/prod.yaml
Reduserer hvor mye CPU vi ber om med 60%
Her er hvor mye vi bruker. I følge [dokumenteringen til Nais](https://doc.nais.io/explanation/good-practices/?h=cp#set-reasonable-resource-requests-and-limits)
skal man sette cpu-requests til hva applikasjonen bruker ved normal
last. Ser det er på ca 1%, men at vi til tider kan gå en del over.
> Reduser CPU-forespørsel

- .github/dependabot.yml
Sjeldent det er breaking changes ved oppdateringer, men synes som oftest det er ganske enkelt å se hvilken avhengighet som har skylda dersom et bygg brekker, og at det er like greit å fikse i samme branch sammen med alle andre oppdateringer.
> Ønsker å ikke dele opp dependabot PRs

- .deploy/preprod.yaml
- .deploy/prod.yaml
- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingController.kt
- src/main/kotlin/no/nav/familie/klage/personopplysninger/PersonopplysningerService.kt
- src/main/kotlin/no/nav/familie/klage/personopplysninger/dto/PersonopplysningerDto.kt
- src/main/kotlin/no/nav/familie/klage/personopplysninger/fullmakt/FullmaktClient.kt
- src/main/kotlin/no/nav/familie/klage/personopplysninger/fullmakt/FullmaktService.kt
- src/main/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlPerson.kt
- src/main/resources/application.yml
- src/main/resources/pdl/søker.graphql
- src/test/kotlin/no/nav/familie/klage/ApplicationLocal.kt
- src/test/kotlin/no/nav/familie/klage/ApplicationLocalPostgres.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FullmaktClientMock.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/OppslagSpringRunnerTest.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/PdlClientMock.kt
- src/test/kotlin/no/nav/familie/klage/personopplysninger/PersonopplysningerServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlDtoTest.kt
- src/test/kotlin/no/nav/familie/klage/personopplysninger/pdl/PdlTestdata.kt
- src/test/kotlin/no/nav/familie/klage/testutil/PdlTestdataHelper.kt
Henter fullmakt fra eget endepunkt. 
Team representasjon tar nå seg av forvaltning av fullmakt. 
Koden for fullmakt ligger fortsatt under pdl: https://github.com/navikt/pdl/tree/master/apps/fullmakt
Tilganger er gitt i dev og prod. Testet i preprod.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-21485)
> Nytt endepunkt fullmakt

- pom.xml
- src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/main/kotlin/no/nav/familie/klage/personopplysninger/fullmakt/FullmaktClient.kt
- src/main/kotlin/no/nav/familie/klage/test/TestController.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieIntegrasjonerMock.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
Lagt til håndtering av BehandlingEventType `BEHANDLING_ETTER_TRYGDERETTEN_OPPHEVET_AVSLUTTET`.
Tolker ut ifra at slack-tråd: https://nav-it.slack.com/archives/C058Z17RTSR/p1725270224706149?thread_ts=1725264080.383119&cid=C058Z17RTSR at det ikke skal gjøres noe med denne type event.
Kontrakt for behandlingDetaljer er funnet her: https://github.com/navikt/kabal-api/pull/1199
> Håndter ny eventtype BEHANDLING_ETTER_TRYGDERETTEN_OPPHEVET_AVSLUTTET

- .deploy/preprod.yaml
- .deploy/prod.yaml
Skrur på NAIS auto-instrumentation, som bruker OpenTelemetry for å samle inn telemetri. I vårt tilfelle tracing-data.
https://docs.nais.io/observability/how-to/auto-instrumentation/
> Legg til auto-instrumentation

- pom.xml
- src/main/kotlin/no/nav/familie/klage/distribusjon/JournalføringUtil.kt
- src/main/kotlin/no/nav/familie/klage/kabal/KabalKafkaListener.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/test/kotlin/no/nav/familie/klage/distribusjon/JournalførBrevTaskTest.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
Nytt utfall og type fra KA -> medhold etter omgjøringskrav. (https://github.com/navikt/familie-kontrakter/pull/965)
"Medhold etter fvl. § 35 KA"
Brukere kan sende krav om at klageinstansen omgjør et av sine tidligere vedtak, og dette kalles omgjøringskrav. Dersom et omgjøringskrav fører til et medhold, må vedtaksinstans kobles på for å effektuere. familie-klage må kunne håndtere hendelser med denne typen og dette utfallet.
> Vil håndtere omgjøringskrav avsluttet 

- .deploy/preprod.yaml
- .deploy/prod.yaml
- src/main/kotlin/no/nav/familie/klage/personopplysninger/fullmakt/FullmaktClient.kt
- src/main/resources/application.yml
**Hvorfor er denne endringen nødvendig? ✨**
Pdl-api har byttet til repr-api, og det er ikke lenge til pdl-api slutter å virke, ref: https://nav-it.slack.com/archives/C020Q1K6EAY/p1732611753116999
Repr-api finnes i gcp og url/scope må byttes til å gå mot gcp i stedet.
Dette må også gjøres for klage.
Testet OK i preprod.
Vi er gitt tilganger her:
https://github.com/navikt/representasjon/blob/cc057eab93023fb4a3d7b5572b6373b3ec5bc8ea/.nais/prod-gcp/repr-api.yaml
> Gå over til å hente fullmakt i GCP

- src/main/kotlin/no/nav/familie/klage/kabal/domain/OversendtKlage.kt
Event av type BEHANDLING_FEILREGISTRERT kan inneholde detaljer med type = OMGJOERINGSKRAV. 
Vil legge til OMGJOERINGSKRAV i Type for å kunne lese eventer av denne typen.
Eksempel på feil i preprod: 
```
value = {"eventId":"66685a8b-7fdf-4a43-afd8-e4aa082bc7f8","kildeReferanse":"abc6","kilde":"IT01","kabalReferanse":"a7847e67-fb33-45f6-a3ca-552f7210986d","type":"BEHANDLING_FEILREGISTRERT","detaljer":{"klagebehandlingAvsluttet":null,"ankebehandlingOpprettet":null,"ankebehandlingAvsluttet":null,"ankeITrygderettenbehandlingOpprettet":null,"behandlingFeilregistrert":{"feilregistrert":"2024-12-02T09:56:09.291636971","navIdent":"Z993258","reason":"E2E-test","type":"OMGJOERINGSKRAV"},"behandlingEtterTrygderettenOpphevetAvsluttet":null,"omgjoeringskravbehandlingAvsluttet":null}})] (Forsøk nr 11) …
```
> Vil håndtere events av type BEHANDLING_FEILREGISTRERT + OMGJOERINGSKRAV

- pom.xml
- src/main/kotlin/no/nav/familie/klage/kabal/KabalService.kt
- src/main/kotlin/no/nav/familie/klage/kabal/domain/OversendtKlage.kt
- src/test/kotlin/no/nav/familie/klage/kabal/KabalServiceTest.kt
Favro: [NAV-23745](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23745) 
Bruker `Fagsystem` fra felles-pakke i kontrakter fremfor fra klage-pakke. Kabal forventer enum verdiene vi har i felles-pakka. Dette medfører ingen endring for EF og BA, men det fører til at vi sender KONT fremfor KS.
> Bruker `Fagsystem` fra kontrakter felles-pakke ved oversending til Kabal 

- src/main/kotlin/no/nav/familie/klage/brev/baks/BaksBrev.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/BaksBrevController.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/BaksBrevHenter.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/BaksBrevOppdaterer.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/BaksBrevOppretter.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/BaksBrevRepository.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/BaksBrevService.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/FritekstBrevRequestDtoUtleder.kt
- src/main/kotlin/no/nav/familie/klage/brev/baks/FritekstbrevHtmlUtleder.kt
- src/main/resources/db/migration/V23__baks_brev.sql
- src/test/kotlin/no/nav/familie/klage/brev/baks/BaksBrevControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/BaksBrevHenterTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/BaksBrevOppdatererTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/BaksBrevOppretterTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/BaksBrevRepositoryTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/BaksBrevServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/BaksBrevTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/FritekstBrevRequestDtoUtlederTest.kt
- src/test/kotlin/no/nav/familie/klage/brev/baks/FritekstbrevHtmlUtlederTest.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/OppslagSpringRunnerTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23920
Legger inn kode for å generere og lagre brev for BAKS. Brevet skiller seg fra EF brevet med at brevmottakerene blir laget i en egen tabell. 
`FritekstBrevRequestDtoUtleder` og `FritekstbrevHtmlUtleder` er kode som er kopiert fra EF sin kode men flyttet inn i egne klasser for å enklere gjenbruke/testes. Tanken er at EF koden også kan benytte disse i en senere PR.
> NAV-23920: Oppretter kode for generering av brev for BAKS

- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingPåVentService.kt
- src/main/kotlin/no/nav/familie/klage/behandlingsstatistikk/BehandlingsstatistikkService.kt
- src/main/kotlin/no/nav/familie/klage/behandlingsstatistikk/BehandlingsstatistikkTask.kt
Vi introduserer statistikk tasks for klagebehandling når den settes/tas av vent. 
Dette har vært vanskelig å teste, så man bare antar at det fungerer. Metodene blir kalt, men resultatet i baksystemene kan ikke verifiseres helt enda.
> Statistikk tasks for klagebehandling som settes og tas av vent

- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingPåVentService.kt
- src/main/kotlin/no/nav/familie/klage/behandling/dto/OppgaveDto.kt
- src/main/kotlin/no/nav/familie/klage/behandling/dto/SettPåVentRequest.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveClient.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveService.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/TilordnetRessursService.kt
- src/test/kotlin/no/nav/familie/klage/behandling/BehandlingPåVentServiceTest.kt
Denne PRen har som hensikt å addresse et funn fra testing, der den som tar behandlingen av vent blir deligert som ansvarlig saksbehandler.
Denne [PRen](https://github.com/navikt/familie-klage/pull/571) depender på denne [PRen](https://github.com/navikt/familie-klage-frontend/compare/main...feature/vent-oppgave-versjon) (front-end).
Funn fra test og oppgave kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22627).
> Feature - deliger oppgave til saksbehandler som tar klagebehandling av vent

- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerController.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerErstatter.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerHenter.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerOppretter.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerService.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerSletter.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/domain/NyBrevmottaker.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/domain/SlettbarBrevmottaker.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/dto/BrevmottakereDto.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/dto/NyBrevmottakerDto.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/dto/SlettbarBrevmottakerDto.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerErstatterTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerHenterTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerOppretterTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerSletterTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/domain/NyBrevmottakerTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/dto/NyBrevmottakerDtoKtTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/dto/SlettbarBrevmottakerDtoKtTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DtoTestUtil.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23920
Relatert frontend PR: https://github.com/navikt/familie-klage-frontend/pull/885
Legger til ny kode for å opprette, endre, slette, osv. brevmottakere. Dette skal i teorien fungere for både EF og BAKS.
> NAV-23920: Legger til ny kode for brevmottakere

- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerOppretter.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerUtil.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/domain/Brevmottaker.kt
- src/main/kotlin/no/nav/familie/klage/distribusjon/JournalførBrevTask.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/domain/BrevmottakerKtTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/dto/BrevmottakereDtoTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23920
Så noen forbedringspotensialer etter merge av forrige PR, tenkte det var greit å ta de i en egen PR. 
Flytter BrevmottakerUtil, korrigerer typos, legger til manglende tester, og forenkler oppretting av BrevmottakerPersonUtenIdent.
Har kjørt opp løsningen lokalt og det ser ut til å fungere fint.
> NAV-23920: Flytter BrevmottakerUtil, korrigerer typos, legger til manglende tester, og forenkler oppretting av BrevmottakerPersonUtenIdent

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
Denne PRen prøver å fjerne deprecated work flow variabler fra bygg og deploy taskene. NAIS har satt og `identity_provider` og `project_id` deprecated og skal fjernes, da alle setter de samme verdiene her og utledes derfor automatisk av nais-plattformen nå. Workflows med disse parameterene satt vil ikke lenger virke etter 3. mars.
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24100).
Dette er en av mange PRer der denne samme endringen gjøres for repoer tilhørende enslig-forsørger.
> Legacy - fjerne deprecated work flow variabler fra build & deploy

- src/main/kotlin/no/nav/familie/klage/kabal/domain/OversendtKlageAnkeV3.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24412
Ser at det er innført en enum av typen `BEHANDLING_ETTER_TRYGDERETTEN_OPPHEVET` i [klage-kodeverk](https://github.com/navikt/klage-kodeverk/blob/main/src/main/kotlin/no/nav/klage/kodeverk/Type.kt#L11). Denne typen mangler i familie-klage. Når man prøver å prosessere kafka meldinger med denne typen får man en feilmelding og meldingen blir ikke prosessert. Det forhindrer at nye meldinger som kommer på topicet blir prosessert. Se [kibana](https://logs.adeo.no/s/nav-logs-legacy/app/discover#/doc/0d8b7d4e-18f5-4cd1-a02f-f53750611e2f/tjenestekall-team-teamfamilie-000003?id=rhWEI5UBHSyLL8t9V15f) for feilmeldingen.
Det er litt uheldig at endringer i deres enum gjør slik at vi ikke får prosessert …
> NAV-24412: Legger til manglende enum som forhindrer proessering av kafka meldinger

- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
Favro: [NAV-24445 ](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24445)
Vi får foreløpig feil når vi sender inn `Barnetrygd`, se [her](https://github.com/navikt/oppgave/pull/574) for mer informasjon.
Vi ønsker å teste hvordan systemet oppfører seg når vi sender inn `Klage`, legger det derfor bak en toggle for KS og BA. 
Togglen er skrudd på i dev.
> NAV-24445: Legger til toggle for å kunne sette behandlingstema til klage

- src/main/kotlin/no/nav/familie/klage/brev/BrevClient.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24383
Per nå så er det hardkodet EF datasett når vi generer html.
Legger derfor på en switch som bruker datasett basert på ytelse.
> Bruker BA eller KS datasett hvis stønadstypen er ks/ba ved generererering av html

- src/main/kotlin/no/nav/familie/klage/brev/BrevClient.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevInnholdUtleder.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
- src/test/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24383
Tanken var å gjøre dette samme måte som EF gjør det med henleggelsesbrev.
Men det er veldig skreddersydd EF, og jeg tenker vi må gjøre BAKS løpet opp mot Sanity en annen gang, som ikke er det kortet her (siden vi ikke bruker sanity per i dag uansett).
> Bruk ba ks datasett hvis stønadstypen er ks ba

- pom.xml
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/main/kotlin/no/nav/familie/klage/kabal/event/BehandlingEventService.kt
Favro: [NAV-24445](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24445)
Vi ønsker å sette `Behandlingstema` til `null` og `Behandlingstype` til `Klage` for BA og KS. 
Tenker å skrive tester senere hvis dette viser seg å fungere. Testfilen burde ryddes litt opp i også så tar det i en egen PR senere. 
Logikken er gjemt bak en toggle.
> NAV-24445: Setter behandlingstema til null og behandlingstype til klage for KS og BA i klagekontekst

- src/main/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingController.kt
- src/test/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DtoTestUtil.kt
Favro: [NAV-24505](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24505)
Har behov for å vite hvilken UUID behandlingen har når den blir opprettet via BA/KS så returnere derfor den i responsen.
> NAV-24505: Oppretting av behandling returnere UUIDen til behandlingen

- src/main/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingController.kt
- src/test/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingControllerTest.kt
Favro: [NAV-24505](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24505)
Har behvor for å returnere `UUID`en til klagebehandlingen ved opprettelse. Tidligere returnerte vi bare `UUID` rått, men må ha det i en `Ressurs` for at det skal fungere korrekt med kallet som blir gjort i BA/KS-sak.
> NAV-24505: Wrapper return type UUID i Ressurs

- src/main/kotlin/no/nav/familie/klage/brev/BrevInnholdUtleder.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/VurderingService.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/VurderingValidator.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/domain/Vurdering.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/dto/VurderingDto.kt
- src/main/resources/db/migration/V24__utvidet_innstilling_klageinstans.sql
- src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
- src/test/kotlin/no/nav/familie/klage/vurdering/VurderingServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/vurdering/VurderingValidatorTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24683)
I klager for barnetrygd og kontantstøtte må saksbehandlerne kunne fylle ut fem felter i innstilling til Nav Klageinstans, i stedet for ett.
- Legger til de fem nye feltene som nullable String på `Vurdering` og `VurderingDto`.
- Endrer validering av `Vurdering` til at de nye feltene må være utfylt dersom fagsystem er BA eller KS, i stedet for `instillingKlageinstans`
- Legger til ny funksjon for generering av opprettholdelsebrev, basert på fagsystem, som lister opp de fem nye feltene som egne avsnitt
Fikser semantikk i overskriftene i brevet i en annen PR
> Utvider innstilling til Nav klageinstans med flere felter

- src/main/kotlin/no/nav/familie/klage/brev/BrevClient.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevInnholdUtleder.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/brev/dto/AvsnittDto.kt
- src/main/kotlin/no/nav/familie/klage/felles/util/TekstUtil.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/test/kotlin/no/nav/familie/klage/brev/BrevInnholdUtlederTest.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/BrevClientMock.kt
For brev fra klageløsningen ønsker vi bedre semantisk HTML for BA og KS
- Legger til enum `Heading` som representerer HTML headings `<h1>`, ..., `<h6>`
- Legger til `deloverskriftHeading` i `AvsnittDto` for å kunne spesifisere hvilken heading deloverskriften skal ha. Defaulter til `null`, som bruker "gammel" HTML i `familie-brev`
- Legger til heading på deloverskrifter for BA og KS sine brev
- Tar i bruk nytt endepunkt i `familie-brev` for BA og KS
[Relatert PR i familie-brev](https://github.com/navikt/familie-brev/pull/770)
**Nye brev**:
> Brev i henhold til visuelle retningslinjer for BA og KS

- src/main/kotlin/no/nav/familie/klage/brev/BrevInnholdUtleder.kt
- src/test/kotlin/no/nav/familie/klage/brev/BrevInnholdUtlederTest.kt
Favro: [NAV-24873](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24873)
Tidligere satt vi alle klagefrister til 6 uker. Nå settes klagefrist til 3 uker for kontantstøtte.
> NAV-24873: Setter klagefrist til 3 uker for kontantstøtte

- src/main/kotlin/no/nav/familie/klage/brev/BrevInnholdUtleder.kt
- src/test/kotlin/no/nav/familie/klage/brev/BrevInnholdUtlederTest.kt
Favro: [NAV-24872](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24872)
Justerer formulering for trukket klage for BA og KS og oppdaterer tilhørende tester.
Endte opp med å slette en test da den tester noe som aldri skal skje i løsningen.
> NAV-24872: Justerer formulering for trukket klage for BA og KS

- src/main/kotlin/no/nav/familie/klage/brev/BrevInnholdUtleder.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/test/kotlin/no/nav/familie/klage/brev/BrevInnholdUtlederTest.kt
Legger til saksbehandlers begrunnelse for hvorfor klagefrist-unntak er oppfylt i "opprettholdelse"-brev.
Teksten legges inn først under underoverskriften "Dokumentasjon og utredning".
Beklageligvis ser det ut til at det er flere endringer enn det som er reelt. Veldig mye er bare ktlint.
> Velger her å ikke opprette nye felter for intern begrunnelse og brevtekst, da vi fortsatt forholdsvis enkelt kan utlede om det er en avvisnings-begrunnelse eller en klagefrist-unntak begrunnelse
Screenshots:
> NAV-24774: Fritekst ved opprettholdelse og klagefrist-unntak oppfylt

- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerErstatter.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerOppretter.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerSletter.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerErstatterTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerOppretterTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerSletterTest.kt
Favro: [NAV-24896](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24896)
Legger til litt mer validerings, samt forbedrer feilmeldingene som allerede eksiterer. 
Koden her er egentlig togglet bort / ikke i bruk, men tenkte det var greit å bare ta det når jeg først så det.
> NAV-24896: Rydder opp i valideringskode for brevmottaker

- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/VurderingController.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/VurderingService.kt
- src/test/kotlin/no/nav/familie/klage/behandling/BehandlingFlytTest.kt
- src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/vurdering/VurderingServiceTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24788)
For behandlinger for BA og KS ønsker vi å kunne lagre vurdering uten å validere at inneholdet er utfylt og å bytte steg.
Legger til nytt endepunkt, og endrer navn på det gamle, for å bedre beskrive sideeffekten
> Legg til endepunkt som lagrer vurdering uten validering og oppdatering av steg

- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakService.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClient.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClient.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieBASakClientMock.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieKSSakClientMock.kt
- src/test/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClientTest.kt
- src/test/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClientTest.kt
Favro: [NAV-24658](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24658)
**Obs! Obs! familie-ba-sak og familie-ks-sak PRene må merges først, ellers må toggelen være skrudd av.**
Har behov for klagebehandling ID når man rapporterer saksstatistikk til DVH. Vi har lyst til at revurdering klage skal peke til klagebehandlingen som er kilden. Tar i dermed i bruk nytt endepunkt som sender med IDen til klagebehandlingen.
Relatert familie-ba-sak PR: https://github.com/navikt/familie-ba-sak/pull/5211
> NAV-24658: Ta i bruk nytt endepunkt for oppretting av revurdering klage for KS og BA

- src/main/kotlin/no/nav/familie/klage/oppgave/TilordnetRessursService.kt
- src/test/kotlin/no/nav/familie/klage/oppgave/TilordnetRessursServiceTest.kt
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24865
Når man henter ansvarlig saksbehandler for behandlingen så hentes først oppgaven.
Vi har oppdaget tilfeller der dette ikke er mulig fordi bruker ikke har tilgang til oppgaven som behandlingen er koblet til.
Dette fører til en uspesifisert feilmelding i frontend.
Catcher derfor forbidden error ved henting av oppgave når man henter ansvarlig saksbehandler og sender en bedre feilmelding tilbake til frontend. Også lagd tester + noe manglende tester for eksisterende kode.
> Fikser bedre feilmelding når det ikke er mulig å hente oppgave grunnet tilgangsfeil

- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/test/kotlin/no/nav/familie/klage/integrasjoner/FeatureToggleMock.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24862
Toggle er skrudd på i prod og trengs ikke lengre. 
Frontend må merges først: https://github.com/navikt/familie-klage-frontend/pull/920
> NAV-24862: Fjerne toggle for å vise brevmottaker BAKS variant

- src/main/kotlin/no/nav/familie/klage/distribusjon/DistribuerBrevTask.kt
- src/main/kotlin/no/nav/familie/klage/distribusjon/DistribusjonService.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieIntegrasjonerClient.kt
- src/test/kotlin/no/nav/familie/klage/distribusjon/DistribuerBrevTaskTest.kt
- src/test/kotlin/no/nav/familie/klage/distribusjon/DistribusjonServiceTest.kt
Legger til løype for å distribuere brev, som sender med adresse for brevmottakere uten ident. For brevmottakere med ident (fnr eller orgnr), sendes `adresse = null`, slik det gjøres allerede
> Løype for distribuering av brev for brevmottakere uten ident

- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClient.kt
- src/test/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClientTest.kt
Favro: [NAV-25020](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25020)
Ble litt mye klipp og lim da jeg implementerte toggelen. Korrigerer slik at man går til korrekt (gammel) url når man ikke har toggelen skrudd på. 
Riktig URL prefix i ba:
> NAV-25020: Korrigerer URL for oppretting av revurdering klage for BA

- src/main/kotlin/no/nav/familie/klage/behandling/enhet/BehandlendeEnhetService.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveClient.kt
- src/main/kotlin/no/nav/familie/klage/oppgave/OppgaveService.kt
- src/test/kotlin/no/nav/familie/klage/behandling/enhet/BehandlendeEnhetServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/oppgave/OppgaveClientTest.kt
- src/test/kotlin/no/nav/familie/klage/oppgave/OppgaveServiceTest.kt
Favro: [NAV-24879](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24879)
All koden her skal være togglet bak toggelen [familie-klage.skal-kunne-endre-behandlende-enhet-baks](https://teamfamilie-unleash-web.iap.nav.cloud.nais.io/projects/default/features/familie-klage.skal-kunne-endre-behandlende-enhet-baks)
Patch-endepunktet i familie-integrasjoner fungerer ikke så bra når man skal tilbakestille/slette verdier, se [her](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-10379).
Tar dermed i bruk et annet endepunkt for å oppdatere enhet på oppgave, inspirert av hvordan det er gjort i [ba-sak](https://github.com/navikt/familie-ba-sak/blob/main/src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasj …
> NAV-24879: Tar i bruk endepunkt for å patche enhet på oppgave

- src/main/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingService.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakService.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClient.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClient.kt
- src/test/kotlin/no/nav/familie/klage/behandling/FerdigstillBehandlingServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/integrasjoner/FagsystemVedtakServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClientTest.kt
- src/test/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClientTest.kt
Favro: [NAV-24658](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24658)
Brukte den intern behandlingId ved en feil. Skal sende over ekstern behandlingId, i likhet med det som er gjort for fagsaken.
> NAV-24658: Endrer oversendt id til eksternBehandlingId ved opprettingav revurdering klage for BA og KS

- kafka/aapen-klage-behandlingsstatistikk/behandlingsstatistikk-topic-dev.yaml
- kafka/aapen-klage-behandlingsstatistikk/behandlingsstatistikk-topic-prod.yaml
Favro: [NAV-25133](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25133)
Har lyst til å kunne lese topicene gjennom kafka manager slik at det blir lettere å feilsøke/grave.
> NAV-25133: Legger familie-baks-kafka-manager i ACL slik at kafka-manager kan lese topicet.

- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
Favro: [NAV-25176](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25176)
Legger til [toggle](https://teamfamilie-unleash-web.iap.nav.cloud.nais.io/projects/default/features/familie-klage.bruk-ny-henlegg-behandling-modal) for å skru av/på ny henlegg behandling dialog.
Relatert frontend PR: https://github.com/navikt/familie-klage-frontend/pull/944
> NAV-25176: Legger til toggle for ny henlegg behandling dialog

- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerController.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerService.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerUtleder.kt
- src/test/kotlin/no/nav/familie/klage/brev/BrevServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerUtlederTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
Favro: [NAV-25011](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25011)
Har behov for et eget endepunkt for å hente ut de initielle brevmottakerne slik at de kan vises i "Henlegg behandling" modalen.
> NAV-25011: Legger til endepunkt for initielle brevmottakere

- src/main/kotlin/no/nav/familie/klage/brev/BrevController.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerController.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerService.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerUtleder.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/domain/Brevmottaker.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/domain/NyBrevmottaker.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/dto/BrevmottakereDto.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/dto/NyBrevmottakerDto.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/dto/SlettbarBrevmottakerDto.kt
- src/main/kotlin/no/nav/familie/klage/distribusjon/JournalførBrevTask.kt
- src/main/kotlin/no/nav/familie/klage/henlegg/HenlagtDto.kt
- src/main/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingController.kt
- src/main/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingDto.kt
- src/main/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingService.kt
- src/main/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingValidator.kt
- src/test/kotlin/no/nav/familie/klage/brev/BrevServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerUtlederTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/domain/BrevmottakerKtTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/domain/NyBrevmottakerTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/dto/NyBrevmottakerDtoKtTest.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/dto/SlettbarBrevmottakerDtoKtTest.kt
- src/test/kotlin/no/nav/familie/klage/distribusjon/JournalførBrevTaskTest.kt
- src/test/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingDtoTest.kt
- src/test/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingValidatorTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DtoTestUtil.kt
Favro: [NAV-25011](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25011)
Relatert front-end PR: https://github.com/navikt/familie-klage-frontend/pull/953
Legger til muligheten for å sette brevmottakere ved henlegging av behandlinger.
> NAV-25011: Legger til manuelle brevmottakere i henlegging av behandling

- src/main/kotlin/no/nav/familie/klage/brev/BrevService.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/VurderingValidator.kt
Justerer validering av vurdering før generering av brev for å unngå duplikat valideringskode, samt endrer `feilHvis` til `brukerFeilHvis` slik at vi ikke logger error når validering feiler. Valideringsfeilene skyldes saksbehandler og ikke systemet.
Det skal i utgangspunktet ikke være mulig å havne i en situasjon hvor man skal generere brev og vurdering-feltene ikke er satt, men det kan skje dersom saksbehandler har samme behandling oppe i 2 vinduer. Denne endringen fører til at saksbehandler får en bedre feilmelding dersom feilen først skulle skje.
Endringen treffer kun BA og KS. Gjelder altså ikke EF.
Relatert slack-tråd: https://nav-it.slack.com/archives/C01G9BA8JKZ/p1750750954944469
> Ungår duplikat validering av vurdering samt kaster ApiFeil fremfor Feil ved manglende utfylt felt for BA/KS

- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleController.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
Fjerner toggle for å legge til brevmottakere.
Må merges etter https://github.com/navikt/familie-klage-frontend/pull/980
> NAV-25804: Fjerner toggle for å legge til brevmottakere

- pom.xml
- src/main/kotlin/no/nav/familie/klage/amelding/InntektController.kt
- src/main/kotlin/no/nav/familie/klage/behandling/BehandlingController.kt
- src/main/kotlin/no/nav/familie/klage/behandlingshistorikk/BehandlingshistorikkController.kt
- src/main/kotlin/no/nav/familie/klage/brev/BrevController.kt
- src/main/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerController.kt
- src/main/kotlin/no/nav/familie/klage/ekstern/EksternBehandlingController.kt
- src/main/kotlin/no/nav/familie/klage/fagsak/FagsakService.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/FormController.kt
- src/main/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingController.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/sikkerhet/TilgangService.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieBASakClient.kt
- src/main/kotlin/no/nav/familie/klage/integrasjoner/FamilieKSSakClient.kt
- src/main/kotlin/no/nav/familie/klage/personopplysninger/PersonopplysningerController.kt
- src/main/kotlin/no/nav/familie/klage/vedlegg/VedleggController.kt
- src/main/kotlin/no/nav/familie/klage/vurdering/VurderingController.kt
- src/test/kotlin/no/nav/familie/klage/brevmottaker/BrevmottakerControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/fagsak/FagsakServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/henlegg/HenleggBehandlingControllerTest.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieBASakClientMock.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/FamilieKSSakClientMock.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/config/OppslagSpringRunnerTest.kt
- src/test/kotlin/no/nav/familie/klage/infrastruktur/sikkerhet/TilgangServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/testutil/DomainUtil.kt
Favro: [NAV-25324](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25324)
Tilgangskontrollen i klage er ulik tilgangskontrollen vi har i ba/ks-sak. Dette fører i noen tilfeller til at saksbehandler ikke har tilgang til klagebehandlingen for en fagsak de har tilgang til i ba/ks-sak. 
I og med at tilgangskontrollen i ba/ks-sak går ut på å sjekke tilgang til alle fagsak-deltagere får vi ikke endret tilgangskontrollen direkte i klageløsningen, da vi ikke vet hvem deltakerne er der. Tilgangskontroll for ba/ks-sak er derfor endret til at vi kjører et kall mot henholdsvis ba-sak og ks-sak og sjekker om saksbehandler har tilgang til den "eksterne" fagsaken. Har saksbehandler tilgang til den "eksterne" fagsaken gir vi saksbehandler tilgang.
Endringen er …
> Egen tilgangskontroll dersom fagsystem er BA eller KS

- src/main/kotlin/no/nav/familie/klage/behandling/enhet/BehandlendeEnhetService.kt
- src/main/kotlin/no/nav/familie/klage/formkrav/FormService.kt
- src/main/kotlin/no/nav/familie/klage/infrastruktur/featuretoggle/FeatureToggleService.kt
- src/test/kotlin/no/nav/familie/klage/behandling/enhet/BehandlendeEnhetServiceTest.kt
- src/test/kotlin/no/nav/familie/klage/formkrav/FormServiceTest.kt
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26083
Fjerner toggle da den har vært skrudd på i prod en stund.
> NAV-26083: Fjerner toggle for å sende endret enhet som behandlingstatistikk
